# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/m2a3g/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),m2a3g)

#include $(CLEAR_VARS)
#LOCAL_MODULE := libGLES_mali
#LOCAL_MODULE_OWNER := samsung
#LOCAL_SRC_FILES := proprietary/vendor/lib/egl/libGLES_mali.so
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_CHECK_ELF_FILES := false
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)/egl

#include $(BUILD_PREBUILT)
endif